[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
orengine = "1.0.0"
# When you aren't testing the performance with Docker, you can use orengine = { path = "../../../../../orengine-rs" }
tokio = { version = "1.45.1", features = ["full"] }
smol = "2.0.0"
async-std = "1.13.1"
flume = { version = "0.11.1", features = ["async"] }