services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
      target: final
    environment:
      - SERVER=orengine
    ports:
      - "8083:8083"

  client:
    build:
      context: client
      dockerfile: Dockerfile
      target: final
    environment:
      - CLIENT=std
    ports:
      - "8081:8081"
    depends_on:
      - server