[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
orengine = { path = "../../../" }
tools = { path = "../../tools" }
tokio = { version = "1", features = ["full"] }
smol = "2.0.0"
async-std = "1.12.0"