cargo-features = ["edition2024"]

[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
orengine = "0.2.3-unstable"
socket2 = { version = "0.5.7", features = ["all"] }
may = "0.3.46"
tokio = { version = "1", features = ["full"] }
smol = "2.0.0"
async-std = "1.12.0"