[package]
name = "cpu-bounded"
version = "0.1.0"
edition = "2021"

[dependencies]
orengine = "0.3.0-unstable"
tokio = { version = "1", features = ["full"] }
smol = "2.0.0"
async-std = "1.12.0"
crossbeam = "0.8.4"