cargo-features = ["edition2024"]

[package]
name = "cpu-bounded"
version = "0.1.0"
edition = "2024"

[dependencies]
orengine = "0.2.3-unstable"
tokio = { version = "1", features = ["full"] }
smol = "2.0.0"
async-std = "1.12.0"
crossbeam = "0.8.4"