name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run tests
        run: |
          cargo test -- --nocapture
          cargo test --all-features -- --nocapture
          cargo test --release -- --nocapture
          cargo test --release --all-features -- --nocapture

  test-windows:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run tests
        shell: cmd
        run: |
          cargo test -- --nocapture
          cargo test --all-features -- --nocapture
          cargo test --release -- --nocapture
          cargo test --release --all-features -- --nocapture

  test-macos:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run tests
        run: |
          cargo test -- --nocapture
          cargo test --all-features -- --nocapture
          cargo test --release -- --nocapture
          cargo test --release --all-features -- --nocapture

  code-style-check-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run tests
        run: |
          cargo fmt --all --check
          cargo clippy
          cargo doc

  code-style-check-windows:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run tests
        shell: cmd
        run: |
          cargo fmt --all --check
          cargo clippy
          cargo doc