name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    name: Build Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Debug
        run: cargo build --verbose

  test-debug:
    name: Test Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Debug
        run: cargo build --verbose
      - name: Run Tests Debug
        run: cargo test --verbose -- --nocapture

  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: cargo build --release --verbose

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Release
        run: cargo build --release --verbose
      - name: Run Tests Release
        run: cargo test --release --verbose -- --nocapture