cargo-features = ["edition2024"]

[package]
name = "test-macro"
version = "1.0.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.76", features = ["proc-macro", "clone-impls", "extra-traits", "parsing", "full"] }
quote = "1.0"
proc-macro2 = "1.0.86"

[lib]
proc-macro = true