[package]
name = "cpu-bound"
version = "0.1.0"
edition = "2021"

[dependencies]
memory-stats = "1.0.0"
orengine = { path = "../../../orengine-rs" }
tokio = { version = "1.45.1", features = ["full"] }
smol = "2.0.0"
async-std = "1.13.1"
may = "0.3.51"

[[bin]]
name = "orengine"
path = "src/orengine.rs"
doc = false

[[bin]]
name = "sync"
path = "src/sync.rs"
doc = false

[[bin]]
name = "smol"
path = "src/smol.rs"
doc = false

[[bin]]
name = "async_std"
path = "src/async_std.rs"
doc = false


[[bin]]
name = "may"
path = "src/may.rs"
doc = false

[[bin]]
name = "tokio"
path = "src/tokio.rs"
doc = false

[profile.release-with-debug]
inherits = "release"
debug = true